version: '3'
services:
  zookeeper:
    image: debezium/zookeeper
    container_name: debezium_zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka
    container_name: debezium_kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: debezium/example-mysql
    container_name: debezium_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "./init.mysql.sql:/docker-entrypoint-initdb.d/inventory.sql"
  postgres:
    image: debezium/postgres
    container_name: debezium_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  connect:
    image: debezium/connect
    container_name: debezium_connect
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
      - postgres
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_connect_configs
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_connect_statuses
  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: debezium_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200